# Generated by Django 4.0.6 on 2022-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_Instructor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Status',
            field=models.CharField(default='Student', max_length=10),
        ),
    ]
