# Generated by Django 4.0.6 on 2022-07-30 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('coursecode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
                ('prof', models.ManyToManyField(related_name='course_prof', to=settings.AUTH_USER_MODEL)),
                ('students_enrolled', models.ManyToManyField(related_name='course_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
