# Generated by Django 4.0.6 on 2022-07-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_alter_assignment_title_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
