# Generated by Django 4.0.6 on 2022-07-30 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grades', '0005_grade_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prof',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='course_instructors', to=settings.AUTH_USER_MODEL),
        ),
    ]
