# Generated by Django 4.0.6 on 2022-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0006_remove_course_prof_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
