# Generated by Django 4.0.6 on 2022-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
