# Generated by Django 4.0.6 on 2022-08-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0008_alter_course_grade'),
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': 'QuestionBank', 'verbose_name_plural': 'QuestionBank'},
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('endTime', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quiz', to='Grades.course')),
                ('questions', models.ManyToManyField(to='Quizzes.questionbank')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
